In [3]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [50]:
%matplotlib inline
def gd(x,y):
    m_curr = b_curr = 0
    n = len(x)
    rate = 0.01
    iter = 100
    for i in range(iter):
        y_pred = m_curr*x + b_curr
        cost = (1/n)*sum([value**2 for value in (y-y_pred)])
        print(m_curr,b_curr,i,cost)
        md = -1*(2/n)*sum(x*(y - y_pred ))
        bd = -1*(2/n)*sum(y-y_pred)
        m_curr = m_curr - rate*md
        
        b_curr = b_curr - rate*bd
        
        

In [23]:
import pandas as pd
d = pd.read_csv('test_scores.csv')

In [51]:
x = d.math
x = np.array(d.math)
print(x)
y = np.array(d.cs)
print(y)

[92 56 88 70 80 49 65 35 66 67]
[98 68 81 80 83 52 66 30 68 73]


In [52]:
gd(x,y)

0 0 0 5199.1
98.918 1.3980000000000001 1 45366108.340850405
-9169.587968000002 -129.386408 2 398290329619.79004
859278.7790833284 12125.168845408005 3 3496779946139640.5
-80513336.3321037 -1136112.3853868274 4 3.0699891720627802e+19
7544007292.656351 106452428.60001147 5 2.6952892837845242e+23
-706864823521.7386 -9974470361.562872 6 2.3663224578744982e+27
66232422560018.44 934596423272.1094 7 2.077506859218773e+31
-6205901966243919.0 -87570612045376.58 8 1.8239419296970382e+35
5.814858905354231e+17 8205265827097408.0 9 1.6013252366146002e+39
-5.448456046050343e+19 -7.688239892447695e+17 10 1.4058794699920812e+43
5.105140772789593e+21 7.203792526577272e+19 11 1.2342883500192473e+47
-4.783458302630841e+23 -6.74987090568644e+21 12 1.0836403571650532e+51
4.482045520657572e+25 6.324551557439078e+23 13 9.513793301690755e+54
-4.1996252038400877e+27 -5.926032210335615e+25 14 8.352610936721472e+58
3.9350006088606955e+29 5.552624156669068e+27 15 7.3331537955360665e+62
-3.6870504009680314e+31 -5.

/home/anurag/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in double_scalars
  if __name__ == '__main__':


In [53]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]
